### ISSUE TITLE
Does not work on VS Code 1.23.1

### ISSUE THREAD

**Issue by dszakal** [pzuraq/vscode-vertical-tab-bar#1]
I followed the steps - installed the extension and added to user settings:

    "vscode_custom_css.imports": [
        "file:///Users/iamdev/.vscode/extensions/pzuraq.vertical-tab-bar-1.0.0/styles.css"
    ]

It does change nothing and says "Unknown configuration setting". The file path is correct, cmd+click opening

(using macOS)

**Comment by capsudo** [comment]
same problem here. I also added `    "vscode_custom_css.policy": true` to user settings.

But I don't have the error "Unknown configuration setting" in user settings, did you install the extension [VS Code Custom CSS plugin](https://github.com/be5invis/vscode-custom-css) ?

Also no error shown in developer tools.

VS code 1.24.1
Ubuntu 18.04

**Comment by dbegent** [comment]
Here's a fix...

I have version 1.25.1 and it doesn't work. From what I can find its due to the changes in the IDE and the class names have changed a little. I had a little play around looking at the **_workbench.main.css_** and **_js_** files and the css below will work. Update this file
**_<path to>\.vscode\extensions\pzuraq.vertical-tab-bar-1.0.0\styles.css_**

I've removed the hiding of the activitybar but left it commented in case you want to keep that. 

The original has .**_monaco-workbench.nosidebar_** to ensure we only go vertical when the sidebar is removed. 

Enjoy.

Now, here's the css
`
/* Flex Tab Bar */

/*.monaco-workbench > .activitybar {
  display: none;
}
.monaco-workbench > .editor {
left: 0 !important;
}

when sidebar hidden
.monaco-workbench.nosidebar
*/


.monaco-workbench > .part.editor > .content  .editor-group-container {
	display: flex;
	flex-direction: row;
}

.monaco-workbench>.part.editor>.content .editor-group-container>.title {
	overflow: visible;
	height: 100%;
	flex-direction: column;
}

.monaco-workbench >.part.editor>.content .editor-group-container>.title .tabs-container {
	flex-direction: column;
	height: 100%;
	width: 200px;
}

.monaco-workbench > .part.editor > .content .editor-group-container > .title .tabs-container > .tab {
	width: 100%;
}


.monaco-workbench .monaco-editor, .monaco-editor .inputarea {
	margin-top: 17px;
}


.monaco-workbench .scroll-decoration {
	display: none !important;
}
`

**Comment by Harag9** [comment]
I use a vertical tabs in Visual Studio and really miss it in VSCode. After finding this was very pleased... until it didn't work. 

VSCode: 1.28.2 64x
Windows 10

I've installed this and put in the path etc to the file, however I get this error too:

"Unknown configuration setting"

I've put in the above css, still no vertical tabs :(

**Comment by dbegent** [comment]
I love vertical tabs in VS so tried to keep it in VSCode. I did have it working but I've recently updated the version and it no longer works. I've not had time to try to get it working in the same manner
I now use (excuse me if I get the name wrong) Open File Explorer. It sits above or below the project explorer but that's the only option. Ideally I'd have it standalone but I can't see how to do that right now. It's ok but I'm so used to single click a tab I'm struggling to get used to having to double click the file I want

**Comment by JavierCane** [comment]
The extension still doesn't work on VS Code 1.31. I'll leave here the process I've followed with some tweaks added to the solution shared by @dbegent just in case it helps anyone 🙂

* Install [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) extension
* `mkdir ~/.vscode/customizations`
* `touch ~/.vscode/customizations/vertical-tab-bar.css`
* `code ~/Library/Application\ Support/Code/User/settings.json`
```json
{
  "workbench.editor.showTabs": true,
  "vscode_custom_css.imports": [
    "file:///Users/%your_username%/.vscode/customizations/vertical-tab-bar.css"
  ],
  "vscode_custom_css.policy": true
}
```
* `code ~/.vscode/customizations/vertical-tab-bar.css`
```css
/* Source: https://github.com/pzuraq/vscode-vertical-tab-bar/issues/1 */

/* Disable CVS and Split editor buttons */
.editor-actions {
  display: none;
}

.monaco-workbench > .part.editor > .content .editor-group-container {
  display: flex;
  flex-direction: row;
}

.monaco-workbench .monaco-editor,
.monaco-editor .inputarea {
  margin-top: 17px;
}

.monaco-workbench .scroll-decoration {
  display: none !important;
}

.monaco-workbench > .part.editor > .content .editor-group-container > .title {
  overflow: visible;
  height: 100%;
  flex-direction: column;
}

.monaco-workbench
  > .part.editor
  > .content
  .editor-group-container
  > .title
  .tabs-container {
  flex-direction: column;
  height: 100%;
  width: 160px;
}

.monaco-workbench
  .part.editor
  > .content
  .editor-group-container
  > .title
  .tabs-container
  > .tab.sizing-fit {
  width: 100%;
  min-width: auto;
}
```
* `Cmd+Shift+P` -> `Reload Custom CSS and JS` -> Restart Visual Studio Code

Result:

<img width="876" alt="vscode_settings json dotfiles unsupported 2019-02-25 12-00-12" src="https://user-images.githubusercontent.com/986235/53333019-04c9fc80-38f5-11e9-8a05-1a5202baba2d.png">

Another option would be using the Explorer sidebar panel > Open Editors section:

* `~/Library/Application\ Support/Code/User/settings.json`: Same as before
* `code ~/.vscode/customizations/vertical-tab-bar.css`
```css
.tabs {
  display: none;
}
```
* `Cmd+Shift+P` -> `Reload Custom CSS and JS` -> Restart Visual Studio Code

Result:

<img width="895" alt="vertical-tab-bar css dotfiles unsupported 2019-02-25 12-12-35" src="https://user-images.githubusercontent.com/986235/53333696-de0cc580-38f6-11e9-9728-87e311bc599f.png">

If anyone wants to modify the Explorer sidebar panel > Open Editors section CSS in order to set more space for each tab, I'll use it for sure 🙂
